### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by labarba** [ericmjl/dl-workshop#14]
I could not find a license for these materials. Did I miss it? If not, would you mind adding a license to know how we can (re)use the tutorial materials? Thanks for writing this!

**Comment by ericmjl** [comment]
@labarba thanks for pinging in! It's going to be MIT-licensed :smile:. Please reuse liberally!

**Comment by mbrukman** [comment]
@ericmjl -- since you've decided to use the MIT license for this project, could you please add a `LICENSE` file to this repo with the contents of the license at https://choosealicense.com/licenses/mit/ or https://opensource.org/licenses/MIT to clarify?

Per [GitHub docs on licensing][github-docs-licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license.

Thanks!

[github-docs-licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

**Comment by ericmjl** [comment]
Apologies for the delay here! I have added the license to the repo. :smile:
